version: '3.8'

services:
  item_service:
    build: ./item_service
    ports:
      - "8081:8081"
    networks:
      - microservices-net

  order_service:
    build: ./order_service
    ports:
      - "8082:8082"
    networks:
      - microservices-net

  payment_service:
    build: ./payment_service
    ports:
      - "8083:8083"
    networks:
      - microservices-net

  api_gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - item_service
      - order_service
      - payment_service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge