server:
  port: 8080

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: http://item_service:8081
          predicates:
            - Path=/items/**
        - id: order-service
          uri: http://order_service:8082
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://payment_service:8083
          predicates:
            - Path=/payments/**